version: '3.8'

services:
  postgres-test:
    image: 'postgres:10.7'
    container_name: 'nodesampleapp_db_test'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 54320:5432
